### ISSUE TITLE
Duplication of included models

### ISSUE THREAD

**Issue by JonathanPrince** [digitalsadhu/loopback-component-jsonapi#111]
Duplication of data under "included" key in response when using `?include=model`

``` js
included: [
{
type: "companies",
id: "1",
attributes: {
address: "1 Main St, USA",
contact: "Rick James",
name: "First Company",
phone: "(03) 555 5555"
}
},
{
type: "companies",
id: "1",
attributes: {
address: "1 Main St, USA",
contact: "Rick James",
name: "First Company",
phone: "(03) 555 5555"
}
},
{
type: "companies",
id: "2",
attributes: {
address: "2 Union Rd, USA",
contact: "Leroy Jenkins",
name: "Second Company",
phone: "(03) 555 1234"
}
},
{
type: "companies",
id: "2",
attributes: {
address: "2 Union Rd, USA",
contact: "Leroy Jenkins",
name: "Second Company",
phone: "(03) 555 1234"
}
},
{
type: "companies",
id: "1",
attributes: {
address: "1 Main St, USA",
contact: "Rick James",
name: "First Company",
phone: "(03) 555 5555"
}
},
{
type: "companies",
id: "2",
attributes: {
address: "2 Union Rd, USA",
contact: "Leroy Jenkins",
name: "Second Company",
phone: "(03) 555 1234"
}
}
]
```

**Comment by leeduc** [comment]
+1

**Comment by digitalsadhu** [comment]
Solution in the works for this.
We have been working on this project which will eventually replace the serialization step in loopback-component-jsonapi include duplication is fixed in loopback-jsonapi-model-serializer
https://github.com/digitalsadhu/loopback-jsonapi-model-serializer

**Comment by ryanxwelch** [comment]
I have a pretty simple fix for this issue in serializer.js. Would it be possible to add me as a contributor?

**Comment by digitalsadhu** [comment]
Hey man, awesome that you are keen to contribute! Could you open a PR with your changes so we can review and discuss before merge?

**Comment by Tronix117** [comment]
Quick fix in a boot file:

```typescript
_  = require('lodash')

module.exports = function(server){
  Object.keys(server.models).forEach((key) => {
    server.models[key].afterJsonApiSerialize = afterJsonApiSerialize
  })
};

function afterJsonApiSerialize(options, cb) {
  if(options.results.included && options.results.included.length) {
    // Remove duplicates
    options.results.included = _.uniqBy(options.results.included, (data)=>{
      return [data.type, data.id].join('/')
    })
  }
  cb(null, options);
}
```

**Comment by markstuart** [comment]
That's a possible solution @Tronix117, the only issue I see is that if you needed to use the `afterJsonApiSerialize` hook in a specific model to transform the data or relationships, you would need to remember to copy the de-duplication code into that hook. Or actually, I think this might prevent you from being able to use the `afterJsonApiSerialize` hook in models since the boot scripts would run after the model loading, and override your custom model hook.

**Comment by Tronix117** [comment]
Yes exactly @markstuart, that's why I flagged it as a "quick fix", until this project implement it directly. We can not directly override the JSONApi parts which fill this `included` attributes, since most of the methods are private.

Nevertheless, if I want to have back a way to define something else to do within my models after the serialize, I can still add something like:

```typescript
if(typeof this.afterSerialize === 'function') {
  this.afterSerialize(options, cb)
} else {
  cb(null, options)
}
```

**Comment by Tronix117** [comment]
Issue should be closed

**Comment by digitalsadhu** [comment]
yup, closing
