### ISSUE TITLE
Create ember js example project

### ISSUE THREAD

**Issue by digitalsadhu** [digitalsadhu/loopback-component-jsonapi#15]
I haven't had time to do this yet. It would be good to test out current functionality and see how it plays with a modern ember/ember data project.

I think it should be a separate repo and we can maintain it over time to show others how to get up and running with loopback and ember.

**Comment by tsteuwer** [comment]
I can take that

**Comment by digitalsadhu** [comment]
Awesome!

**Comment by tsteuwer** [comment]
Go ahead and assign it to me.

**Comment by digitalsadhu** [comment]
@tsteuwer assigned! 
I've added you as a collaborator as well.

**Comment by tsteuwer** [comment]
Ok, I have a complete working example with tests on the front-end hooking into a loopback backend. It is basically an array of methods which return a promise of whether the test worked or failed. I can also start adding more test as the component moves along. I ended up calling it [emberloop](https://github.com/tsteuwer/emberloop). The only thing I want to do is get the models up-to-date with their unit tests so that it's a "complete" application. Once that's done, I think I'll release a 1.0.0 version if that's ok with everyone? Also, feel free to go test it out!

**Comment by digitalsadhu** [comment]
I'm going to fire this up again today and take another look.

**Comment by digitalsadhu** [comment]
@tsteuwer This is looking really great! 
I was able to get the docker containers running and ran the tests and had a look through the ember test code. Super nice to have the integration confirmation! Nice work!

**Comment by tsteuwer** [comment]
Yep! I'm going to add filter functions and coalesce find requests when I get home. I'll then add a link on the component read me for integration with Ember so people can start looking at it. Would that be ok?

**Comment by digitalsadhu** [comment]
Yup sounds great!
