### ISSUE TITLE
serialize a remote method's response

### ISSUE THREAD

**Issue by BenjaminHorn** [digitalsadhu/loopback-component-jsonapi#45]
First of all thanks for this awesome component. Finally Ember and loopback work nicely together.

I have the following issue:

``` javascript
module.exports = function(Foo) {


  Foo.bar = function(id, cb) {
    Foo.findById(id,{}, function(err, base){
      // ...
      Foo.find({}, function(err, foos) {
        foos.forEach(function(foo){
          // ... some logic here ...
        });

        cb(null, foos); // <-- needs some formatting
      });
    });
  }

 Foo.remoteMethod(
      'bar', 
      { 
        accepts: {arg: 'id', type: 'Number', required: true},
        returns: {arg: 'foos'},
        http: {path: '/:id/foo-bar'}
      }
  );
};
```

The problem, that the playload will have the loopback format, so I can't do

``` javascript
let self = this;
this.get('ajax').call('POST', record.constructor.modelName, record.get('id'), 'foo-bar').then(function(res){
  self.store.pushPayload('foo', res);
}
```

because res wont have **JSON API** format.
How should I serialize **foos** before I send it back in the callback?

**Comment by digitalsadhu** [comment]
Thanks for reporting! 

I'll just note, while the parts of the component that are implemented have a tonne of unit tests, this is absolutely early days, long way to go. (Im taking another full day tomorrow to work on it)

Having said that I'm really, really happy to get some feedback so thanks for trying it out!

To your issue. For now, I'm intentionally scoping which methods return as JSON API so as to avoid potential unintended side effects. In your particular case I can see that it would make perfect sense for the returned data to be automatically formatted as JSON api, the trouble I have is that in many cases a remote method will be an entirely custom piece of data. Consider:

```js
Foo.isBig = function (cb) {
  // work out if its big then
  cb(null, true)
}

Foo.remoteMethod(
      'isBig', 
      { 
        returns: {arg: 'value', type: 'boolean'},
        http: {path: '/isBig'}
      }
  );
```

I couldn't really automatically JSON API this response. I'm not sure how I could differentiate between a remote method such as yours where it makes sense to automatically JSON API the data and one like isBig where it doesn't. If you have any ideas, I'm all ears.

Otherwise, I would recommend doing the transform as part of your remote method definition. Manually transform it before putting it into the callback. You could consider this module: https://www.npmjs.com/package/jsonapi-serializer It takes care of the basic structure for you.

Hope that helps.

**Comment by BenjaminHorn** [comment]
Thanks @digitalsadhu for your quick response! 

I think my case is rather an exception, and your example is more common, so you are right about not handling them the same.
I took a look at your code and I found https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/serialize.js#L10. Does it mean that you take all remote methods (including **bar** from my example) and (JSON API) serialize their results? Probably not, because it is not what happening. 

If I do

```javascript
  Foo.afterRemote('bar', function( ctx, modelInstance, next) { 
    ctx.result = "baz";
    next();
  });
```

then my response will be "baz".  Maybe it would a good solution to have the serialization exported separately so one could do

```javascript
  var serialize = require('../../node_modules/loopback-component-jsonapi/serialize');
  Foo.afterRemote('bar', function( ctx, modelInstance, next) { 
    var res = serialize(ctx, next);
    ctx.result = res;
    next();
  });
```

**Comment by digitalsadhu** [comment]
Yea, we explicitly scope which methods get serialization applied here:
https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/serialize.js#L12-L26
So that custom remote methods don't get serialized.

I like where you are going with this idea. 

I'd like to get some feedback on the idea from @listepo and @tsteuwer What do you guys think? How should we handle giving people a way to serialise remote methods into JSON API format without knowing about what sort of output people want from their remote methods?


JSON api at a minimum needs everything to be on a root level `data` key and we can also always work out the `self` link from the url so we do provide a serialiser that as a minimum transforms remote method output from something like:
```js
{
  myKey: { /*...my data... */}
}
```
to
```js
{
  links: { 
    self: 'http://thecurrenturl' 
  },
  data: {
   myKey: { /*...my data... */}
  }
}
```

This isn't valid JSON API however since there needs to be a resource id and data should be on an `attributes` key inside the `data` object but its a start.

**Comment by BenjaminHorn** [comment]
Just an another idea: https://github.com/digitalsadhu/loopback-component-jsonapi/blob/master/lib/serialize.js#L12-L26 could be extendable in **component-config.json**.

**Comment by digitalsadhu** [comment]
Hmm. Yea that's probably a really good way to do it!

**Comment by tsteuwer** [comment]
@digitalsadhu, I don't see an issue with exposing the serializer, but I honestly think we should flesh-out the component before starting work on things like this. Just my two cents.

**Comment by digitalsadhu** [comment]
@tsteuwer Agreed. We need to go for broke on the core functionality. 
Looks like we are going to use it at work shortly making this approach even more important. Also means I should get a little work time to work on it.

**Comment by digitalsadhu** [comment]
This functionality is now available as of 0.14.0
You will need to use: the `include` option to tell the component which method(s) to serialize/deserialize and you will most likely need to use one of the new serialization hooks to clean up the output. See the readme for:
- `include`
- `afterJsonApiSerialize`

**Comment by Tronix117** [comment]
I'm commenting here because it's about it, I don't think it should be at component's level to configure this behavior, but rather within the definition of the remoteMethod, ex:

```
Foo.remoteMethod(
      'isBig', 
      { 
        returns: {arg: 'value', type: 'boolean', jsonapi: true},
        http: {path: '/isBig'}
      }
);
```

I think I will do a PR for that.

**Comment by digitalsadhu** [comment]
Nice idea. 

I think you may want to expand on this a little. Ideally you'd be able to configure a remote method to be serialized as a specific model in most cases otherwise all you can do is make sure the output is of the form:
```js
{
  id: '...',
  type: '...',
  attributes: {...}
}
```
As soon as you have a model as a serialization target you can do a lot more. You can work out the type, relations etc. 

I guess if you introspected the remote defn's type and match it against models in the system you could do that.

```js
Foo.remoteMethod(
      'myComments', 
      { 
        returns: {arg: 'value', type: 'Comment', jsonapi: true},
        http: {path: '/my-comments'}
      }
);
```
